# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import random

browser = webdriver.Firefox()

#random user
user = random.randint(10000,99999)

browser.get("http://localhost:8001/")
browser.set_window_size(827, 713)
browser.find_element(By.LINK_TEXT, "Register").click()
browser.find_element(By.ID, "username").click()
browser.find_element(By.ID, "username").send_keys(f"{user}")
time.sleep(0.5)
browser.find_element(By.ID, "displayname").send_keys(f"{user}")
time.sleep(0.5)
browser.find_element(By.ID, "email").click()
browser.find_element(By.ID, "email").send_keys(f"{user}")
time.sleep(0.5)
browser.find_element(By.ID, "password").send_keys(f"{user}")
time.sleep(0.5)
browser.find_element(By.ID, "password2").send_keys(f"{user}")
time.sleep(0.5)
browser.find_element(By.ID, "Register").click()
time.sleep(0.5)
browser.find_element(By.LINK_TEXT, "Login").click()
browser.find_element(By.ID, "username").click()
browser.find_element(By.ID, "username").send_keys(f"{user}")
time.sleep(0.5)
browser.find_element(By.ID, "password").send_keys(f"{user}")
browser.find_element(By.ID, "Login").click()
time.sleep(2)
browser.get("http://localhost:8001/user/promote")
browser.set_window_size(827, 713)
time.sleep(5)
browser.find_element(By.LINK_TEXT, f"{user}").click()
browser.find_element(By.LINK_TEXT, "Logout").click()
browser.find_element(By.LINK_TEXT, "Login").click()
browser.find_element(By.ID, "username").click()
browser.find_element(By.ID, "username").send_keys(f"{user}")
time.sleep(0.5)
browser.find_element(By.ID, "password").send_keys(f"{user}")
time.sleep(0.5)
browser.find_element(By.ID, "password").send_keys(Keys.ENTER)
time.sleep(0.5)
browser.find_element(By.LINK_TEXT, "Admin").click()

